# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: roBOT test

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - name: Black Code Formatter
      uses: lgeiger/black-action@v1.0.1
    - name: Lint Action
      uses: wearerequired/lint-action@v1.10.0
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
          python-version: ${{ matrix.python-version }}    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install -r requirements.txt --upgrade pip    
    - name: Run script
      id: build
      env:
          TOKEN: ${{ secrets.TOKEN }}
          MONGO: ${{ secrets.MONGO }}
      run: |
        python main.py
        echo ::set-output name=exit_code::$?

    - name: Run exit_code check
      if: steps.build.outputs.exit_code == 0
